name: Update note RSS mirror

on:
  schedule:
    - cron: '0 */6 * * *'   # 6時間ごと（お好みで）
  workflow_dispatch:        # 手動実行も可
  push:
    paths:
      - .github/workflows/update-note-feed.yml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch note RSS
        run: |
          mkdir -p note
          curl -L --fail --compressed "https://note.com/loyal_dill1011/rss" -o note/feed.xml
      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'note/feed.xml'
          message: 'chore: update note RSS mirror'
