name: Update note feed (RSS -> JSON)

on:
  schedule:
    - cron: "15 0 * * *"   # 毎日09:15 JST（00:15 UTC）
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate note-feed.json from RSS
        run: |
          python scripts/fetch_note_feed.py \
            "https://note.com/loyal_dill1011/m/m9a97295e24a9/rss/" \
            "note-feed.json"

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update note-feed.json from RSS"
          file_pattern: note-feed.json
